### ISSUE TITLE
Double Posting all rolls

### ISSUE THREAD

**Issue by Asmenedas** [NathanHawks/SR1eGameBot#13]
Hi Nathan,

As of today (5/21/22 - just noticed about an hour ago), GameBot is posting two roll results for every !x command on my Discord. Is there any idea why or what can be done to correct that? Please let me know.

Thanks.

Asmenedas

![image](https://user-images.githubusercontent.com/19398695/169664343-505a69ea-284a-47e4-9889-8c25e89de68f.png)

**Comment by NathanHawks** [comment]
Whoops! Two copies of the bot were running! Thanks for letting me know!

**Comment by Asmenedas** [comment]
Can confirm correction.

Thank you!

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
